name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install DB
        uses: getong/mariadb-action@v1.1
        with:
          mysql root password: ${{ secrets.mariaRootPassword }} # Required if "mysql user" is empty, default is empty. The root superuser password
          mysql user: 'codecs' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
          mysql password: ${{ secrets.mariaCodecsPassword }} # Required if "mysql user" exists. The password for the "mysql user"
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Install DB
        run: bash ./.github/db.sh
      - name: Build with Maven
        run: mvn clean install
