name: Java CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Shutdown Ubuntu MySQL (SUDO)
          run: sudo service mysql stop
      - uses: mirromutth/mysql-action@v1.1
        with:
          character set server: 'utf8'
          collation server: 'utf8_general_ci'
          mysql database: 'codecs'
          mysql root password: root
          mysql user: 'codecs'
          mysql password: 'codecs'
      - name: Install SQLs
        run: |
          sudo apt-get install dos2unix
          cd data/
          ./execute.sh root
          cd ..
      - name: Build And Test with Maven
        run: mvn clean install -Dspring.datasource.username=root -Dspring.datasource.password=root
      - name: Repackage Jar
        run: mvn package spring-boot:repackage -DskipTests=true
      - name: copy back to DEV
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.devURL }}
          username: ${{ secrets.devUser }}
          password: ${{ secrets.devPassword }}
          port: 22
          source: "target/codecs-0.0.1-SNAPSHOT.jar"
          target: "/home/codecs/"
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm ci and npm run build
        run: |
          cd front/
          echo $(pwd)
          npm ci
          npm run build:ci
          /bin/tar -czf dist.tgz ./dist
      - name: copy front to DEV
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.devURL }}
          username: ${{ secrets.devUser }}
          password: ${{ secrets.devPassword }}
          port: 22
          source: "front/dist.tgz"
          target: "/home/codecs/"